### ISSUE TITLE
Long and possibly multiple exceptions while using the package

### ISSUE THREAD

**Issue by vbmade2000** [CellProfiler/python-bioformats#156]
I am using python-bioformats to read TIFF file. I get following this everytime.

```
09:04:19.664 [Thread-0] DEBUG loci.common.NIOByteBufferProvider - Using mapped byte buffer? false
09:04:19.675 [Thread-0] DEBUG loci.formats.ClassList - Could not find loci.formats.in.URLReader
java.lang.ClassNotFoundException: loci.formats.in.URLReader
	at java.net.URLClassLoader.findClass(URLClassLoader.java:387) ~[na:1.8.0_312]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[na:1.8.0_312]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352) ~[na:1.8.0_312]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[na:1.8.0_312]
	at java.lang.Class.forName0(Native Method) ~[na:1.8.0_312]
	at java.lang.Class.forName(Class.java:264) ~[na:1.8.0_312]
	at loci.formats.ClassList.parseLine(ClassList.java:196) [bioformats_package.jar:6.6.0]
	at loci.formats.ClassList.parseFile(ClassList.java:258) [bioformats_package.jar:6.6.0]
	at loci.formats.ClassList.<init>(ClassList.java:138) [bioformats_package.jar:6.6.0]
09:04:19.677 [Thread-0] DEBUG loci.formats.ClassList - Could not find loci.formats.in.SlideBook6Reader
java.lang.ClassNotFoundException: loci.formats.in.SlideBook6Reader
	at java.net.URLClassLoader.findClass(URLClassLoader.java:387) ~[na:1.8.0_312]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[na:1.8.0_312]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352) ~[na:1.8.0_312]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[na:1.8.0_312]
	at java.lang.Class.forName0(Native Method) ~[na:1.8.0_312]
	at java.lang.Class.forName(Class.java:264) ~[na:1.8.0_312]
	at loci.formats.ClassList.parseLine(ClassList.java:196) [bioformats_package.jar:6.6.0]
	at loci.formats.ClassList.parseFile(ClassList.java:258) [bioformats_package.jar:6.6.0]
	at loci.formats.ClassList.<init>(ClassList.java:138) [bioformats_package.jar:6.6.0]
09:04:19.677 [Thread-0] DEBUG loci.formats.ClassList - Could not find loci.formats.in.ScreenReader
java.lang.ClassNotFoundException: loci.formats.in.ScreenReader
	at java.net.URLClassLoader.findClass(URLClassLoader.java:387) ~[na:1.8.0_312]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[na:1.8.0_312]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352) ~[na:1.8.0_312]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[na:1.8.0_312]
	at java.lang.Class.forName0(Native Method) ~[na:1.8.0_312]
	at java.lang.Class.forName(Class.java:264) ~[na:1.8.0_312]
	at loci.formats.ClassList.parseLine(ClassList.java:196) [bioformats_package.jar:6.6.0]
	at loci.formats.ClassList.parseFile(ClassList.java:258) [bioformats_package.jar:6.6.0]
	at loci.formats.ClassList.<init>(ClassList.java:138) [bioformats_package.jar:6.6.0]
09:04:19.677 [Thread-0] DEBUG loci.formats.ClassList - Could not find loci.formats.in.ZarrReader
java.lang.ClassNotFoundException: loci.formats.in.ZarrReader
	at java.net.URLClassLoader.findClass(URLClassLoader.java:387) ~[na:1.8.0_312]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[na:1.8.0_312]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352) ~[na:1.8.0_312]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[na:1.8.0_312]
	at java.lang.Class.forName0(Native Method) ~[na:1.8.0_312]
	at java.lang.Class.forName(Class.java:264) ~[na:1.8.0_312]
	at loci.formats.ClassList.parseLine(ClassList.java:196) [bioformats_package.jar:6.6.0]
	at loci.formats.ClassList.parseFile(ClassList.java:258) [bioformats_package.jar:6.6.0]
	at loci.formats.ClassList.<init>(ClassList.java:138) [bioformats_package.jar:6.6.0]
09:04:19.881 [Thread-0] DEBUG loci.formats.ClassList - Could not find loci.formats.in.URLReader
java.lang.ClassNotFoundException: loci.formats.in.URLReader
	at java.net.URLClassLoader.findClass(URLClassLoader.java:387) ~[na:1.8.0_312]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[na:1.8.0_312]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352) ~[na:1.8.0_312]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[na:1.8.0_312]
	at java.lang.Class.forName0(Native Method) [na:1.8.0_312]
	at java.lang.Class.forName(Class.java:264) [na:1.8.0_312]
	at loci.formats.ClassList.parseLine(ClassList.java:196) [bioformats_package.jar:6.6.0]
	at loci.formats.ClassList.parseFile(ClassList.java:258) [bioformats_package.jar:6.6.0]
	at loci.formats.ClassList.<init>(ClassList.java:138) [bioformats_package.jar:6.6.0]
	at loci.formats.ClassList.<init>(ClassList.java:122) [bioformats_package.jar:6.6.0]
	at loci.formats.ImageReader.getDefaultReaderClasses(ImageReader.java:80) [bioformats_package.jar:6.6.0]
	at loci.formats.in.FilePatternReader.<init>(FilePatternReader.java:67) [bioformats_package.jar:6.6.0]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) [na:1.8.0_312]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) [na:1.8.0_312]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) [na:1.8.0_312]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) [na:1.8.0_312]
	at java.lang.Class.newInstance(Class.java:442) [na:1.8.0_312]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_312]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_312]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_312]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_312]
	at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:126) [rhino-1.7R4.jar:1.7R4]
	at org.mozilla.javascript.NativeJavaMethod.call(NativeJavaMethod.java:225) [rhino-1.7R4.jar:1.7R4]
	at org.mozilla.javascript.optimizer.OptRuntime.callProp0(OptRuntime.java:85) [rhino-1.7R4.jar:1.7R4]
	at org.mozilla.javascript.gen._java_python_bridge__1._c_script_0(<java-python-bridge>:6) [rhino-1.7R4.jar:na]
	at org.mozilla.javascript.gen._java_python_bridge__1.call(<java-python-bridge>) [rhino-1.7R4.jar:na]
	at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:394) [rhino-1.7R4.jar:1.7R4]
	at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3091) [rhino-1.7R4.jar:1.7R4]
	at org.mozilla.javascript.gen._java_python_bridge__1.call(<java-python-bridge>) [rhino-1.7R4.jar:na]
	at org.mozilla.javascript.gen._java_python_bridge__1.exec(<java-python-bridge>) [rhino-1.7R4.jar:na]
	at org.mozilla.javascript.Context.evaluateString(Context.java:1079) [rhino-1.7R4.jar:1.7R4]
09:04:19.881 [Thread-0] DEBUG loci.formats.ClassList - Could not find loci.formats.in.SlideBook6Reader
java.lang.ClassNotFoundException: loci.formats.in.SlideBook6Reader
	at java.net.URLClassLoader.findClass(URLClassLoader.java:387) ~[na:1.8.0_312]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[na:1.8.0_312]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352) ~[na:1.8.0_312]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[na:1.8.0_312]
	at java.lang.Class.forName0(Native Method) [na:1.8.0_312]
	at java.lang.Class.forName(Class.java:264) [na:1.8.0_312]
	at loci.formats.ClassList.parseLine(ClassList.java:196) [bioformats_package.jar:6.6.0]
	at loci.formats.ClassList.parseFile(ClassList.java:258) [bioformats_package.jar:6.6.0]
	at loci.formats.ClassList.<init>(ClassList.java:138) [bioformats_package.jar:6.6.0]
	at loci.formats.ClassList.<init>(ClassList.java:122) [bioformats_package.jar:6.6.0]
	at loci.formats.ImageReader.getDefaultReaderClasses(ImageReader.java:80) [bioformats_package.jar:6.6.0]
	at loci.formats.in.FilePatternReader.<init>(FilePatternReader.java:67) [bioformats_package.jar:6.6.0]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) [na:1.8.0_312]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) [na:1.8.0_312]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) [na:1.8.0_312]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) [na:1.8.0_312]
	at java.lang.Class.newInstance(Class.java:442) [na:1.8.0_312]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_312]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_312]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_312]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_312]
	at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:126) [rhino-1.7R4.jar:1.7R4]
	at org.mozilla.javascript.NativeJavaMethod.call(NativeJavaMethod.java:225) [rhino-1.7R4.jar:1.7R4]
	at org.mozilla.javascript.optimizer.OptRuntime.callProp0(OptRuntime.java:85) [rhino-1.7R4.jar:1.7R4]
	at org.mozilla.javascript.gen._java_python_bridge__1._c_script_0(<java-python-bridge>:6) [rhino-1.7R4.jar:na]
	at org.mozilla.javascript.gen._java_python_bridge__1.call(<java-python-bridge>) [rhino-1.7R4.jar:na]
	at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:394) [rhino-1.7R4.jar:1.7R4]
	at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3091) [rhino-1.7R4.jar:1.7R4]
	at org.mozilla.javascript.gen._java_python_bridge__1.call(<java-python-bridge>) [rhino-1.7R4.jar:na]
	at org.mozilla.javascript.gen._java_python_bridge__1.exec(<java-python-bridge>) [rhino-1.7R4.jar:na]
	at org.mozilla.javascript.Context.evaluateString(Context.java:1079) [rhino-1.7R4.jar:1.7R4]
09:04:19.882 [Thread-0] DEBUG loci.formats.ClassList - Could not find loci.formats.in.ScreenReader
java.lang.ClassNotFoundException: loci.formats.in.ScreenReader
	at java.net.URLClassLoader.findClass(URLClassLoader.java:387) ~[na:1.8.0_312]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[na:1.8.0_312]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352) ~[na:1.8.0_312]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[na:1.8.0_312]
	at java.lang.Class.forName0(Native Method) [na:1.8.0_312]
	at java.lang.Class.forName(Class.java:264) [na:1.8.0_312]
	at loci.formats.ClassList.parseLine(ClassList.java:196) [bioformats_package.jar:6.6.0]
	at loci.formats.ClassList.parseFile(ClassList.java:258) [bioformats_package.jar:6.6.0]
	at loci.formats.ClassList.<init>(ClassList.java:138) [bioformats_package.jar:6.6.0]
	at loci.formats.ClassList.<init>(ClassList.java:122) [bioformats_package.jar:6.6.0]
	at loci.formats.ImageReader.getDefaultReaderClasses(ImageReader.java:80) [bioformats_package.jar:6.6.0]
	at loci.formats.in.FilePatternReader.<init>(FilePatternReader.java:67) [bioformats_package.jar:6.6.0]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) [na:1.8.0_312]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) [na:1.8.0_312]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) [na:1.8.0_312]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) [na:1.8.0_312]
	at java.lang.Class.newInstance(Class.java:442) [na:1.8.0_312]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_312]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_312]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_312]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_312]
	at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:126) [rhino-1.7R4.jar:1.7R4]
	at org.mozilla.javascript.NativeJavaMethod.call(NativeJavaMethod.java:225) [rhino-1.7R4.jar:1.7R4]
	at org.mozilla.javascript.optimizer.OptRuntime.callProp0(OptRuntime.java:85) [rhino-1.7R4.jar:1.7R4]
	at org.mozilla.javascript.gen._java_python_bridge__1._c_script_0(<java-python-bridge>:6) [rhino-1.7R4.jar:na]
	at org.mozilla.javascript.gen._java_python_bridge__1.call(<java-python-bridge>) [rhino-1.7R4.jar:na]
	at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:394) [rhino-1.7R4.jar:1.7R4]
	at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3091) [rhino-1.7R4.jar:1.7R4]
	at org.mozilla.javascript.gen._java_python_bridge__1.call(<java-python-bridge>) [rhino-1.7R4.jar:na]
	at org.mozilla.javascript.gen._java_python_bridge__1.exec(<java-python-bridge>) [rhino-1.7R4.jar:na]
	at org.mozilla.javascript.Context.evaluateString(Context.java:1079) [rhino-1.7R4.jar:1.7R4]
09:04:19.882 [Thread-0] DEBUG loci.formats.ClassList - Could not find loci.formats.in.ZarrReader
java.lang.ClassNotFoundException: loci.formats.in.ZarrReader
	at java.net.URLClassLoader.findClass(URLClassLoader.java:387) ~[na:1.8.0_312]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[na:1.8.0_312]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352) ~[na:1.8.0_312]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[na:1.8.0_312]
	at java.lang.Class.forName0(Native Method) [na:1.8.0_312]
	at java.lang.Class.forName(Class.java:264) [na:1.8.0_312]
	at loci.formats.ClassList.parseLine(ClassList.java:196) [bioformats_package.jar:6.6.0]
	at loci.formats.ClassList.parseFile(ClassList.java:258) [bioformats_package.jar:6.6.0]
	at loci.formats.ClassList.<init>(ClassList.java:138) [bioformats_package.jar:6.6.0]
	at loci.formats.ClassList.<init>(ClassList.java:122) [bioformats_package.jar:6.6.0]
	at loci.formats.ImageReader.getDefaultReaderClasses(ImageReader.java:80) [bioformats_package.jar:6.6.0]
	at loci.formats.in.FilePatternReader.<init>(FilePatternReader.java:67) [bioformats_package.jar:6.6.0]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) [na:1.8.0_312]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) [na:1.8.0_312]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) [na:1.8.0_312]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) [na:1.8.0_312]
	at java.lang.Class.newInstance(Class.java:442) [na:1.8.0_312]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_312]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_312]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_312]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_312]
	at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:126) [rhino-1.7R4.jar:1.7R4]
	at org.mozilla.javascript.NativeJavaMethod.call(NativeJavaMethod.java:225) [rhino-1.7R4.jar:1.7R4]
	at org.mozilla.javascript.optimizer.OptRuntime.callProp0(OptRuntime.java:85) [rhino-1.7R4.jar:1.7R4]
	at org.mozilla.javascript.gen._java_python_bridge__1._c_script_0(<java-python-bridge>:6) [rhino-1.7R4.jar:na]
	at org.mozilla.javascript.gen._java_python_bridge__1.call(<java-python-bridge>) [rhino-1.7R4.jar:na]
	at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:394) [rhino-1.7R4.jar:1.7R4]
	at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3091) [rhino-1.7R4.jar:1.7R4]
	at org.mozilla.javascript.gen._java_python_bridge__1.call(<java-python-bridge>) [rhino-1.7R4.jar:na]
	at org.mozilla.javascript.gen._java_python_bridge__1.exec(<java-python-bridge>) [rhino-1.7R4.jar:na]
	at org.mozilla.javascript.Context.evaluateString(Context.java:1079) [rhino-1.7R4.jar:1.7R4]
09:04:19.897 [Thread-0] DEBUG o.s.nativelib.NativeLibraryUtil - processor is INTEL_64 os.arch is amd64
09:04:19.897 [Thread-0] DEBUG o.s.nativelib.NativeLibraryUtil - architecture is LINUX_64 os.name is linux
09:04:19.898 [Thread-0] DEBUG o.s.nativelib.NativeLibraryUtil - architecture is LINUX_64 os.name is linux
09:04:19.898 [Thread-0] DEBUG o.s.nativelib.NativeLibraryUtil - platform specific path is META-INF/lib/linux_64/
09:04:19.898 [Thread-0] DEBUG o.scijava.nativelib.BaseJniExtractor - mappedLib is libturbojpeg.so
09:04:19.898 [Thread-0] DEBUG o.scijava.nativelib.BaseJniExtractor - URL is jar:file:/home/vbmade2000/Documents/new_oa/bioformat/venv/lib/python3.8/site-packages/bioformats/jars/bioformats_package.jar!/META-INF/lib/linux_64/libturbojpeg.so
09:04:19.898 [Thread-0] DEBUG o.scijava.nativelib.BaseJniExtractor - URL path is file:/home/vbmade2000/Documents/new_oa/bioformat/venv/lib/python3.8/site-packages/bioformats/jars/bioformats_package.jar!/META-INF/lib/linux_64/libturbojpeg.so
09:04:19.902 [Thread-0] DEBUG o.scijava.nativelib.BaseJniExtractor - Extracting 'jar:file:/home/vbmade2000/Documents/new_oa/bioformat/venv/lib/python3.8/site-packages/bioformats/jars/bioformats_package.jar!/META-INF/lib/linux_64/libturbojpeg.so' to '/tmp/libturbojpeg4805853447258276507.so'
09:04:19.968 [Thread-0] DEBUG loci.common.services.ServiceFactory - Loaded properties from: services.properties
09:04:19.968 [Thread-0] DEBUG loci.common.services.ServiceFactory - Added interface interface loci.formats.services.POIService and implementation class loci.formats.services.POIServiceImpl
09:04:19.968 [Thread-0] DEBUG loci.common.services.ServiceFactory - Added interface interface loci.formats.services.MDBService and implementation class loci.formats.services.MDBServiceImpl
09:04:19.968 [Thread-0] DEBUG loci.common.services.ServiceFactory - Added interface interface loci.formats.services.JPEGTurboService and implementation class loci.formats.services.JPEGTurboServiceImpl
09:04:19.969 [Thread-0] DEBUG loci.common.services.ServiceFactory - Added interface interface ome.codecs.services.LuraWaveService and implementation class ome.codecs.services.LuraWaveServiceImpl
09:04:19.969 [Thread-0] DEBUG loci.common.services.ServiceFactory - Added interface interface loci.common.services.S3ClientService and implementation class loci.common.services.S3ClientServiceImpl
09:04:19.969 [Thread-0] DEBUG loci.common.services.ServiceFactory - Added interface interface loci.formats.services.JAIIIOService and implementation class loci.formats.services.JAIIIOServiceImpl
09:04:19.969 [Thread-0] DEBUG loci.common.services.ServiceFactory - Added interface interface loci.formats.services.WlzService and implementation class loci.formats.services.WlzServiceImpl
09:04:19.970 [Thread-0] DEBUG loci.common.services.ServiceFactory - Added interface interface loci.formats.services.JHDFService and implementation class loci.formats.services.JHDFServiceImpl
09:04:19.970 [Thread-0] DEBUG loci.common.services.ServiceFactory - Added interface interface loci.formats.services.NetCDFService and implementation class loci.formats.services.NetCDFServiceImpl
09:04:19.970 [Thread-0] DEBUG loci.common.services.ServiceFactory - Added interface interface loci.formats.services.EXIFService and implementation class loci.formats.services.EXIFServiceImpl
09:04:19.970 [Thread-0] DEBUG loci.common.services.ServiceFactory - Added interface interface loci.formats.services.MetakitService and implementation class loci.formats.services.MetakitServiceImpl
09:04:19.970 [Thread-0] DEBUG loci.common.services.ServiceFactory - Added interface interface loci.formats.services.LuraWaveService and implementation class loci.formats.services.LuraWaveServiceImpl
09:04:19.971 [Thread-0] DEBUG loci.common.services.ServiceFactory - Added interface interface loci.formats.services.OMEXMLService and implementation class loci.formats.services.OMEXMLServiceImpl
09:04:19.971 [Thread-0] DEBUG loci.common.services.ServiceFactory - Added interface interface ome.codecs.services.JAIIIOService and implementation class ome.codecs.services.JAIIIOServiceImpl
09:04:19.971 [Thread-0] DEBUG loci.common.services.ServiceFactory - Added interface interface loci.formats.services.JPEGXRService and implementation class loci.formats.services.JPEGXRServiceImpl
09:04:19.991 [Thread-0] DEBUG loci.formats.FormatHandler - TiffReader initializing /tmp/MOSA-PHH-04_11_T0001F001L01A01Z01C01.tif
09:04:19.991 [Thread-0] DEBUG loci.formats.FormatHandler - loci.formats.in.TiffReader.initFile(/tmp/MOSA-PHH-04_11_T0001F001L01A01Z01C01.tif)
09:04:19.993 [Thread-0] INFO  loci.formats.in.MinimalTiffReader - Reading IFDs
09:04:20.003 [Thread-0] INFO  loci.formats.in.MinimalTiffReader - Populating metadata
09:04:20.009 [Thread-0] INFO  loci.formats.in.TiffReader - Checking comment style
09:04:20.009 [Thread-0] INFO  loci.formats.in.BaseTiffReader - Populating OME metadata
09:04:20.010 [Thread-0] DEBUG loci.common.DateTools - Invalid timestamp '20210204 11:17:35.363' for current locale
09:04:20.010 [Thread-0] DEBUG loci.common.DateTools - Could not parse timestamp '20210204 11:17:35.363' with EN_US locale
java.lang.IllegalArgumentException: Invalid format: "20210204 11:17:35" is malformed at " 11:17:35"
	at org.joda.time.format.DateTimeFormatter.parseDateTime(DateTimeFormatter.java:871) ~[bioformats_package.jar:6.6.0]
	at org.joda.time.Instant.parse(Instant.java:98) ~[bioformats_package.jar:6.6.0]
	at loci.common.DateTools.parseDate(DateTools.java:291) [bioformats_package.jar:6.6.0]
	at loci.common.DateTools.formatDate(DateTools.java:357) [bioformats_package.jar:6.6.0]
	at loci.common.DateTools.formatDate(DateTools.java:432) [bioformats_package.jar:6.6.0]
	at loci.common.DateTools.formatDate(DateTools.java:416) [bioformats_package.jar:6.6.0]
	at loci.formats.in.BaseTiffReader.initMetadataStore(BaseTiffReader.java:430) [bioformats_package.jar:6.6.0]
	at loci.formats.in.TiffReader.initMetadataStore(TiffReader.java:236) [bioformats_package.jar:6.6.0]
	at loci.formats.in.BaseTiffReader.initMetadata(BaseTiffReader.java:98) [bioformats_package.jar:6.6.0]
	at loci.formats.in.BaseTiffReader.initFile(BaseTiffReader.java:586) [bioformats_package.jar:6.6.0]
	at loci.formats.FormatReader.setId(FormatReader.java:1421) [bioformats_package.jar:6.6.0]
	at loci.formats.in.TiffDelegateReader.setId(TiffDelegateReader.java:92) [bioformats_package.jar:6.6.0]
09:04:20.010 [Thread-0] DEBUG loci.common.DateTools - Invalid timestamp '20210204 11:17:35.363' for current locale
09:04:20.010 [Thread-0] DEBUG loci.common.DateTools - Could not parse timestamp '20210204 11:17:35.363' with EN_US locale
java.lang.IllegalArgumentException: Invalid format: "20210204 11:17:35" is malformed at "210204 11:17:35"
	at org.joda.time.format.DateTimeFormatter.parseDateTime(DateTimeFormatter.java:871) ~[bioformats_package.jar:6.6.0]
	at org.joda.time.Instant.parse(Instant.java:98) ~[bioformats_package.jar:6.6.0]
	at loci.common.DateTools.parseDate(DateTools.java:291) [bioformats_package.jar:6.6.0]
	at loci.common.DateTools.formatDate(DateTools.java:357) [bioformats_package.jar:6.6.0]
	at loci.common.DateTools.formatDate(DateTools.java:432) [bioformats_package.jar:6.6.0]
	at loci.common.DateTools.formatDate(DateTools.java:416) [bioformats_package.jar:6.6.0]
	at loci.formats.in.BaseTiffReader.initMetadataStore(BaseTiffReader.java:430) [bioformats_package.jar:6.6.0]
	at loci.formats.in.TiffReader.initMetadataStore(TiffReader.java:236) [bioformats_package.jar:6.6.0]
	at loci.formats.in.BaseTiffReader.initMetadata(BaseTiffReader.java:98) [bioformats_package.jar:6.6.0]
	at loci.formats.in.BaseTiffReader.initFile(BaseTiffReader.java:586) [bioformats_package.jar:6.6.0]
	at loci.formats.FormatReader.setId(FormatReader.java:1421) [bioformats_package.jar:6.6.0]
	at loci.formats.in.TiffDelegateReader.setId(TiffDelegateReader.java:92) [bioformats_package.jar:6.6.0]
09:04:20.010 [Thread-0] DEBUG loci.common.DateTools - Invalid timestamp '20210204 11:17:35.363' for current locale
09:04:20.010 [Thread-0] DEBUG loci.common.DateTools - Could not parse timestamp '20210204 11:17:35.363' with EN_US locale
java.lang.IllegalArgumentException: Invalid format: "20210204 11:17:35" is malformed at "210204 11:17:35"
	at org.joda.time.format.DateTimeFormatter.parseDateTime(DateTimeFormatter.java:871) ~[bioformats_package.jar:6.6.0]
	at org.joda.time.Instant.parse(Instant.java:98) ~[bioformats_package.jar:6.6.0]
	at loci.common.DateTools.parseDate(DateTools.java:291) [bioformats_package.jar:6.6.0]
	at loci.common.DateTools.formatDate(DateTools.java:357) [bioformats_package.jar:6.6.0]
	at loci.common.DateTools.formatDate(DateTools.java:432) [bioformats_package.jar:6.6.0]
	at loci.common.DateTools.formatDate(DateTools.java:416) [bioformats_package.jar:6.6.0]
	at loci.formats.in.BaseTiffReader.initMetadataStore(BaseTiffReader.java:430) [bioformats_package.jar:6.6.0]
	at loci.formats.in.TiffReader.initMetadataStore(TiffReader.java:236) [bioformats_package.jar:6.6.0]
	at loci.formats.in.BaseTiffReader.initMetadata(BaseTiffReader.java:98) [bioformats_package.jar:6.6.0]
	at loci.formats.in.BaseTiffReader.initFile(BaseTiffReader.java:586) [bioformats_package.jar:6.6.0]
	at loci.formats.FormatReader.setId(FormatReader.java:1421) [bioformats_package.jar:6.6.0]
	at loci.formats.in.TiffDelegateReader.setId(TiffDelegateReader.java:92) [bioformats_package.jar:6.6.0]
09:04:20.012 [Thread-0] DEBUG loci.formats.FormatTools - Expected positive value for PhysicalSize; got 0.0
09:04:20.012 [Thread-0] DEBUG loci.formats.FormatTools - Expected positive value for PhysicalSize; got 0.0

```

Is there a way to suppress/resolve this?

**Comment by Eafergan** [comment]
i am getting same issue after installing bioformat on a new computer with windows 11. From a search on the web it seems as it is just the debug log and it does actually work. I have tried several tip on how to turn the debug messages off but nothing worked. Also this came after lots of issues with Javabridge requirement during the pip installation.

hope someone have some insight please.

**Comment by Eafergan** [comment]
Adding this script to the beginning of the code worked for me... and I had tried many different solutions this is the only one that worked.
Credit: The guys from this page https://forum.image.sc/t/python-bioformats-and-javabridge-debug-messages/12578/11

import javabridge
import bioformats

myloglevel="ERROR"  # user string argument for logLevel.

javabridge.start_vm(class_path=bioformats.JARS)

rootLoggerName = javabridge.get_static_field("org/slf4j/Logger","ROOT_LOGGER_NAME", "Ljava/lang/String;")
rootLogger = javabridge.static_call("org/slf4j/LoggerFactory","getLogger", "(Ljava/lang/String;)Lorg/slf4j/Logger;", rootLoggerName)
logLevel = javabridge.get_static_field("ch/qos/logback/classic/Level",myloglevel, "Lch/qos/logback/classic/Level;")
javabridge.call(rootLogger, "setLevel", "(Lch/qos/logback/classic/Level;)V", logLevel)

# ..your code here..

javabridge.kill_vm()



All the best,
Nati
