### ISSUE TITLE
Error on "from bioformats import log4j"

### ISSUE THREAD

**Issue by braymp** [CellProfiler/python-bioformats#53]
When starting CPA with bioformats 1.0.7 installed, I get the following error:
```
Traceback (most recent call last):
  File "C:/Users/brayma2/Desktop/GitHub/CellProfiler-Analyst/CellProfiler-Analyst.py", line 556, in <module>
    app.Start()
  File "C:/Users/brayma2/Desktop/GitHub/CellProfiler-Analyst/CellProfiler-Analyst.py", line 476, in Start
    from bioformats import log4j
ImportError: cannot import name log4j
```
I'm assuming this is a bioformats issue?

**Comment by braymp** [comment]
Workaround: Fall back to 1.0.6.

**Comment by LeeKamentsky** [comment]
OK should be fixed mark, please check whether pip uninstall python-bioformats and pip install python-bioformats fixes.

**Comment by braymp** [comment]
That did it; thanks!
